spring.profiles.active=local
spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT_NUMBER}
#information to the framework on how to convert
#HQL into native SQL queries
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#create table if not exists & update if exists
spring.jpa.hibernate.ddl-auto=update
#simplest way to dump the queries to standard out
spring.jpa.properties.hibernate.show_sql=true
#To beautify or pretty print the SQL
spring.jpa.properties.hibernate.format_sql=true
#To activate query comments in Hibernate
spring.jpa.properties.hibernate.use_sql_comments=true
#disable the OSIV
spring.jpa.open-in-view=false
